name: MinecraftManhunt
version: '${project.version}'
main: me.tsvrn9.minecraftmanhunt.MinecraftManhunt
api-version: '1.21'

commands:
  minecraftmanhunt:
    aliases: mm
  shout: # used by the private_chat feature
    aliases: s